version: '3'

services:
  app:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yashedo
    depends_on:
      - db
      - test-db
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
  test-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3306"
volumes:
  db-volume:
    

  
  

  

